name: slackbot-ultimate-template
services:
  server:
    ports:
      - 3000:3000
    image: ghcr.io/kcoderhtml/slackbot-ultimate-template:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SLACK_LOG_CHANNEL=C07ALMZQK8T
      - SLACK_BOT_TOKEN=xoxb-
      - SLACK_USER_TOKEN=xoxp-
      - SLACK_SIGNING_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - ADMINS=U0xxxxxxxxx # comma separated list of slack user IDs
    init: true
    volumes:
      - ./data:/app/prisma/data